name: Android CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk11
        arguments: --build-cache build

    - name: Upload app-debug.apk artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload app-release.apk artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
        
    - name: 🚀 Upload APK to GitHub Release
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        name: Release ${{ github.run_number }}
        tag_name: v${{ github.run_number }}
        files: |
          app/build/outputs/apk/debug/app-debug.apk
          app/build/outputs/apk/release/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
